// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfruhexbfxtxqvcvjbmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mcnVoZXhiZnh0eHF2Y3ZqYm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNTk4MjYsImV4cCI6MjA4ODYzNTgyNn0.tCwkC6T1wAR9rWkGEZ2w4d7l4Abfs9YgTpuigjntqRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});